name: update awesome-stars
on:
  workflow_dispatch:
  schedule:
  # 19:00 UTC is 4:00 JST
  - cron: 30 19 * * *
jobs:
  awesome-stars:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install starred==3.2.0
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: starred --username ${{ github.repository_owner }} --repository awesome-stars --sort --token ${GITHUB_TOKEN} --message 'stars update by github actions cron'
